const CONSTANTS = {
  HTTP_CODES: {
    SUCCESS: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTES: 501,
    BAD_GATEWAY: 502,
    SERVICE_UNAVILABLE: 503,
  },
  ERROR_MESSAGES: {
    SUCCESS: "SUCCESS",
    CREATED: "CREATED",
    ACCEPTED: "ACCEPTED",
    NO_CONTENT: "NO_CONTENT",
    BAD_REQUEST: "BAD_REQUEST",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
    NOT_IMPLEMENTES: "NOT_IMPLEMENTES",
    BAD_GATEWAY: "BAD_GATEWAY",
    SERVICE_UNAVILABLE: "SERVICE_UNAVILABLE",
    SOMETHING_WENT_WRONG: "SOMETHING WENT WRONG",
    TOO_MANY_REQUEST_MSG:
      "Too many requests, please try again after 20 minutes.",
  },
};

module.exports = CONSTANTS;
